spring:
  application:
    name: config
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/wmy0436/SpringCloud.git
          search-paths: config/application
          username: wmy0436
          password: mY19921220
    bus:
      refresh:
        enabled: true


management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

